 # Table of Contents
<div class="toc" style="margin-top: 1em;"><ul class="toc-item" id="toc-level0"><li><span><a href="http://10.129.2.170:3904/notebooks/Experiment1.ipynb#Exp-1-T.Baldwin-&amp;-Su-Nam-Kim-NC-Experiment-Based-On-Wordnet-Similarity" data-toc-modified-id="Exp-1-T.Baldwin-&amp;-Su-Nam-Kim-NC-Experiment-Based-On-Wordnet-Similarity-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Exp-1 T.Baldwin &amp; Su Nam Kim NC-Experiment Based On Wordnet Similarity</a></span><ul class="toc-item"><li><span><a href="http://10.129.2.170:3904/notebooks/Experiment1.ipynb#Reading-Data" data-toc-modified-id="Reading-Data-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Reading Data</a></span></li><li><span><a href="http://10.129.2.170:3904/notebooks/Experiment1.ipynb#Find-Similarities" data-toc-modified-id="Find-Similarities-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Find Similarities</a></span></li><li><span><a href="http://10.129.2.170:3904/notebooks/Experiment1.ipynb#Checking-Results" data-toc-modified-id="Checking-Results-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Checking Results</a></span></li></ul></li><li><span><a href="http://10.129.2.170:3904/notebooks/Experiment1.ipynb#Parallel" data-toc-modified-id="Parallel-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Parallel</a></span><ul class="toc-item"><li><span><a href="http://10.129.2.170:3904/notebooks/Experiment1.ipynb#Background" data-toc-modified-id="Background-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Background</a></span></li><li><span><a href="http://10.129.2.170:3904/notebooks/Experiment1.ipynb#Parallel-for-bkgrnd" data-toc-modified-id="Parallel-for-bkgrnd-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Parallel for bkgrnd</a></span></li></ul></li><li><span><a href="http://10.129.2.170:3904/notebooks/Experiment1.ipynb#Singular-Plural-noun-mapping" data-toc-modified-id="Singular-Plural-noun-mapping-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Singular-Plural noun mapping</a></span><ul class="toc-item"><li><span><a href="http://10.129.2.170:3904/notebooks/Experiment1.ipynb#Using-predefined-fix-mapping" data-toc-modified-id="Using-predefined-fix-mapping-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Using predefined fix mapping</a></span></li><li><span><a href="http://10.129.2.170:3904/notebooks/Experiment1.ipynb#Using-an-library" data-toc-modified-id="Using-an-library-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Using an library</a></span></li></ul></li><li><span><a href="http://10.129.2.170:3904/notebooks/Experiment1.ipynb#New-Section" data-toc-modified-id="New-Section-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>New Section</a></span></li><li><span><a href="http://10.129.2.170:3904/notebooks/Experiment1.ipynb#extracting-features-from-sentence" data-toc-modified-id="extracting-features-from-sentence-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>extracting features from sentence</a></span><ul class="toc-item"><li><span><a href="http://10.129.2.170:3904/notebooks/Experiment1.ipynb#verb_list" data-toc-modified-id="verb_list-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>verb_list</a></span></li><li><span><a href="http://10.129.2.170:3904/notebooks/Experiment1.ipynb#Finding-common-ancestor" data-toc-modified-id="Finding-common-ancestor-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Finding common ancestor</a></span></li></ul></li><li><span><a href="http://10.129.2.170:3904/notebooks/Experiment1.ipynb#TO-DO" data-toc-modified-id="TO-DO-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>TO-DO</a></span></li></ul></div>

# Exp-1 T.Baldwin & Su Nam Kim NC-Experiment Based On Wordnet Similarity

## Reading Data 

In [208]:
import pandas as pd
data = pd.read_csv('SC08.all.txt',header=None,sep=' ',usecols=[0,1,2])
data.dropna()

data.head()

0          1      2
0  coalition      force   HAVE
1    summary       form   HAVE
2   computer     system   INST
3    kitchen       door   HAVE
4      media  programme  ABOUT

In [209]:
count=0
for i in data.values[-100:]:
    if i[2] == 'purpose' :
        count += 1
count 

0

## Find Similarities

In [210]:
from nltk.corpus import wordnet as wn
from tqdm import tqdm

In [211]:
matrix = data.values

#print matrix
# it is known that data has 2168 rows we keep last 500 for test others are training set.

limit = 100

train_data = matrix[:-limit]
test_data  = matrix[-limit:]

true_labels = []
pred_labels = []


for i, test in (enumerate( test_data)):
    
    if i % 10 == 0:
        print i

    test_m_syn = wn.synsets( test[0] )
    test_h_syn = wn.synsets( test[1] )
    if test_m_syn and test_h_syn:
        test_m_syn = test_m_syn[0]
        test_h_syn = test_h_syn[0]
    else:
       # print i, test
        continue

    best_score = -10
    best_label = ''
    for j, train in enumerate(train_data):
                
        train_m_syn = wn.synsets( train[0] )
        train_h_syn = wn.synsets( train[1] )
        if train_m_syn and train_h_syn:
            train_m_syn = train_m_syn[0]
            train_h_syn = train_h_syn[0]
        else:
            #print j, train
            continue
        
        m = train_m_syn.wup_similarity( test_m_syn )
        h = train_h_syn.wup_similarity( test_h_syn )
        
        if not m or not h:
            #print test_m_syn, test_h_syn, train_m_syn, train_h_syn
            #print i, j, m, h, test, train
            continue
            
        score = (m + h) / 2
        if score > best_score:
            best_label = train[2]
            best_score = score
            
    true_labels.append( test[2] )
    pred_labels.append( best_label )
        #print(m," ",h)

0
10
20
30
40
50
60
70
80
90


In [213]:
count = 0
for t, p in zip(true_labels, pred_labels):
    if t == p:
        count += 1
        
len(true_labels), count
print (count*1.)/len(true_labels)
print len(true_labels)

0.51
100


In [214]:
import numpy as np

In [215]:

# This is good when we have single labels for test and prediction
# This will not work 'as expected' in case we have multiple labels possible.
'''
true_np = np.array( true_labels )
pred_np = np.array( pred_labels )

(true_np == pred_np).sum() * 1. / true_np.shape[0]
'''
#set(true_labels)
#set(pred_labels)
#Code for multiple labels

count = 0
for i, j in zip(true_labels, pred_labels):

        if set( i.split('/') ).intersection( set(j.split('/')) ):
            count += 1
count


51

In [216]:
from sklearn.metrics import classification_report, confusion_matrix

In [217]:
print len(true_labels)
print len(pred_labels)

100
100


In [218]:
print classification_report(true_labels, pred_labels, digits=4)

             precision    recall  f1-score   support

      ABOUT     0.6471    0.6471    0.6471        17
      ACTOR     0.6667    0.6667    0.6667        21
         BE     0.3846    0.6250    0.4762         8
       HAVE     0.2857    0.3333    0.3077        12
         IN     0.5263    0.3704    0.4348        27
       INST     0.4375    0.4667    0.4516        15

avg / total     0.5228    0.5100    0.5102       100



## Checking Results

In [220]:
#checking results for purpose tag.
result = zip(pred_labels , true_labels)
result
c1=0
c2=0
c3=0
c4=0
for i in result :
    #false-neg
    if i[0] != 'purpose' and i[1]=='purpose':
        c1+=1
    #true-neg
    elif not(i[0]=='purpose') and not(i[1]=='purpose'):
        c2+=1
    #false-pos
    elif (i[0]=='purpose') and not(i[1]=='purpose'):
        c3+=1
    #true-pos
    else:
        c4+=1
prec = (c4 * 1.) / (c4+c3)
rec  = (c4 * 1.) / (c4+c1)
fscore = (2.*prec * rec) / (prec+rec)
print('prec ',prec)
print('rec',rec)
print('fscore',fscore)



ZeroDivisionError: float division by zero

pred_labels

set(true_labels)
set(pred_labels)

In [11]:
#true_labels = ['1', 'agent', 'b', 'agent', 'f', 'a', 'b', '1', '2', '2', '2', '1']
#pred_labels = ['a', 'agent', 'a', 'agent', 'f', 'f', 'b', '1', '3', '2', 'agent', '1']

from sklearn.metrics import confusion_matrix
import pandas as pd

all_labels = set(true_labels).union( set(pred_labels) )
all_labels = list(all_labels)
all_labels.sort()
print all_labels
conf = confusion_matrix(true_labels, pred_labels, labels=all_labels)
print conf

df = pd.DataFrame(conf, columns=all_labels)
df.index = all_labels
df

all_labels = set(['w', 1,2,3]).union( set([2,4,5, 'a']) )
print all_labels
all_labels = list(all_labels)
all_labels.sort()
all_labels

# Parallel

## Background

In [13]:
lamd_fun = lambda a, b: a * b

In [17]:
[lamd_fun(i, i) for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [20]:
map(lamd_fun, range(10), range(10,20))

[0, 11, 24, 39, 56, 75, 96, 119, 144, 171]

In [21]:
map(lambda i, j: i+j, range(10), range(10,20))

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

In [25]:
reduce(lambda i, j: i+j, range(10))

45

## Parallel for bkgrnd

In [221]:
def fun(train_nc):
    
    if not test_m_syn or not test_h_syn:
        return -10, ''

    train_m_syn = wn.synsets( train_nc[0] )
    train_h_syn = wn.synsets( train_nc[1] )
    if train_m_syn and train_h_syn:
        train_m_syn = train_m_syn[0]
        train_h_syn = train_h_syn[0]
    else:
        return -10, ''

    m = train_m_syn.wup_similarity( test_m_syn )
    h = train_h_syn.wup_similarity( test_h_syn )

    if not m or not h:
        return -10, ''
    
    score = (m + h) / 2
    
    return score, train_nc[2]

In [99]:
print fun(['worker', 'protest', 'agent'])
print fun(['Hongkong', 'protest', 'location'])

(0.20526315789473684, 'agent')
(-10, '')


In [113]:
test_nc = 'student protest'
d = map(fun, train_data)
result = reduce(lambda x, y: x if x[0] > y[0] else y, d)
result

(0.5707070707070707, 'topic')

In [222]:
pred_labels = []
train_data = matrix[:-limit]
test_data  = matrix[-limit:]
for test_nc in tqdm(test_data):
    test_m_syn = wn.synsets( test_nc[0] )
    test_h_syn = wn.synsets( test_nc[1] )
    if test_m_syn and test_h_syn:
        test_m_syn = test_m_syn[0]
        test_h_syn = test_h_syn[0]
        
        d = map(fun, train_data)
        result = reduce(lambda x, y: x if x[0] > y[0] else y, d)
        
    else:
        result = (-10, '')
    pred_labels.append( result )
    
pred_labels

100%|██████████| 100/100 [00:47<00:00,  2.11it/s]


[(0.7602339181286549, 'BE'),
 (0.7105263157894737, 'IN'),
 (0.9285714285714286, 'HAVE'),
 (0.9285714285714286, 'BE'),
 (0.6875, 'IN'),
 (0.76890756302521, 'IN'),
 (0.7738095238095238, 'IN'),
 (0.6787330316742082, 'ACTOR'),
 (0.7424242424242424, 'ACTOR'),
 (0.8455882352941176, 'IN'),
 (0.8095238095238095, 'INST'),
 (0.6458333333333333, 'HAVE'),
 (0.6428571428571428, 'HAVE'),
 (0.6666666666666666, 'IN'),
 (0.7733333333333333, 'ACTOR'),
 (0.8333333333333333, 'ABOUT'),
 (0.5833333333333333, 'ACTOR'),
 (0.7, 'ABOUT'),
 (0.7948717948717949, 'ACTOR'),
 (0.7272727272727273, 'IN'),
 (0.6907894736842105, 'ABOUT'),
 (0.8585526315789473, 'ACTOR'),
 (0.7, 'INST'),
 (0.8125, 'IN'),
 (0.8285714285714285, 'ACTOR'),
 (0.8529411764705883, 'ACTOR'),
 (0.7386363636363636, 'ABOUT'),
 (0.7246963562753037, 'HAVE'),
 (0.8157894736842105, 'ACTOR'),
 (0.7602339181286549, 'IN'),
 (0.8, 'IN'),
 (0.6936274509803921, 'INST'),
 (0.6805555555555556, 'INST'),
 (0.6491228070175439, 'HAVE'),
 (0.7291666666666667, 'BE'),

In [223]:
pred_lb = []
true_lb = []
for i in pred_labels:
    pred_lb.append(i[1])
print len(pred_lb)
print len(true_labels)



100
100


In [224]:
from sklearn.metrics import classification_report, confusion_matrix

In [227]:
import numpy as np

In [229]:
print classification_report(true_labels, pred_lb, digits=4)

             precision    recall  f1-score   support

      ABOUT     0.6471    0.6471    0.6471        17
      ACTOR     0.6500    0.6190    0.6341        21
         BE     0.3846    0.6250    0.4762         8
       HAVE     0.2857    0.3333    0.3077        12
         IN     0.5000    0.3704    0.4255        27
       INST     0.4375    0.4667    0.4516        15

avg / total     0.5122    0.5000    0.5008       100



In [232]:
print set(true_labels) 
print set(pred_lb)

set(['BE', 'ABOUT', 'ACTOR', 'INST', 'HAVE', 'IN'])
set(['BE', 'ABOUT', 'ACTOR', 'INST', 'HAVE', 'IN'])


In [233]:
from sklearn.metrics import confusion_matrix
import pandas as pd

In [235]:
all_labels = set(true_labels).union( set(pred_lb) ) 
all_labels = list(all_labels)
all_labels.sort()
print all_labels 
conf = confusion_matrix(true_labels, pred_lb, labels=all_labels)
print conf

['ABOUT', 'ACTOR', 'BE', 'HAVE', 'IN', 'INST']
[[11  0  1  0  2  3]
 [ 1 13  1  2  4  0]
 [ 0  0  5  1  1  1]
 [ 1  2  2  4  1  2]
 [ 3  3  4  4 10  3]
 [ 1  2  0  3  2  7]]


In [236]:
#to manually print confusion matrix take set of both predicted and actual and iterate over both lists.
def print_cm(cm, labels, hide_zeroes=False, hide_diagonal=False, hide_threshold=None):
    """pretty print for confusion matrixes"""
    columnwidth = max([len(x) for x in labels]+[5]) # 5 is value length
    empty_cell = " " * columnwidth
    # Print header
    print "    " + empty_cell,
    for label in labels: 
        print "%{0}s".format(columnwidth) % label,
    print
    # Print rows
    for i, label1 in enumerate(labels):
        print "    %{0}s".format(columnwidth) % label1,
        for j in range(len(labels)): 
            cell = "%{0}.1f".format(columnwidth) % cm[i, j]
            if hide_zeroes:
                cell = cell if float(cm[i, j]) != 0 else empty_cell
            if hide_diagonal:
                cell = cell if i != j else empty_cell
            if hide_threshold:
                cell = cell if cm[i, j] > hide_threshold else empty_cell
            print cell,
        print


In [237]:
print_cm(conf,all_labels)

          ABOUT ACTOR    BE  HAVE    IN  INST
    ABOUT  11.0   0.0   1.0   0.0   2.0   3.0
    ACTOR   1.0  13.0   1.0   2.0   4.0   0.0
       BE   0.0   0.0   5.0   1.0   1.0   1.0
     HAVE   1.0   2.0   2.0   4.0   1.0   2.0
       IN   3.0   3.0   4.0   4.0  10.0   3.0
     INST   1.0   2.0   0.0   3.0   2.0   7.0


In [238]:
from nltk.metrics import ConfusionMatrix

In [242]:
cm1 = ConfusionMatrix(true_labels,pred_lb)
print cm1

      |  A  A             |
      |  B  C     H     I |
      |  O  T     A     N |
      |  U  O  B  V  I  S |
      |  T  R  E  E  N  T |
------+-------------------+
ABOUT |<11> .  1  .  2  3 |
ACTOR |  1<13> 1  2  4  . |
   BE |  .  . <5> 1  1  1 |
 HAVE |  1  2  2 <4> 1  2 |
   IN |  3  3  4  4<10> 3 |
 INST |  1  2  .  3  2 <7>|
------+-------------------+
(row = reference; col = test)



In [132]:
import numpy as np

One more dataset:
_/home/development/girish/datasets/NC-EN/SC08.all.txt_

In [ ]:
data = df.values
np.random.shuffle(data)
df_ = pd.DataFrame(data, columns=df.columns)

# Singular-Plural noun mapping

## Using predefined fix mapping

In [49]:
import requests
import pandas as pd

**Sources:**
* [Plural Nouns Plus Worksheets: EnchantedLearning.com](http://www.enchantedlearning.com/grammar/partsofspeech/nouns/plurals/)
* [A List of 100 Irregular Plural Nouns in English](https://www.thoughtco.com/irregular-plural-nouns-in-english-1692634)
* []()

In [64]:
# Source for list of singlular-to-plural nouns.
url = 'http://www.enchantedlearning.com/grammar/partsofspeech/nouns/plurals/'

r = requests.get( url )
tables = pd.read_html(r.text, header=0)

In [65]:
#tables[5].values[0][2] = 'Hi'
tables[5]

Type of Noun  \
0                       Word ends in s, x, ch, or sh   
1                                     Word ends in z   
2                  Ending in 'y' preceded by a vowel   
3              Ending in 'y' preceded by a consonant   
4      Ends with 'f' or 'fe' (but not 'ff' or 'ffe')   
5                                      Ends with 'o'   
6                                          Irregular   
7                 Ends with 'is' (from a Greek root)   
8     Ends with 'us' (if the word is from the Latin)   
9                                     Ends with 'um'   
10    Ends with 'a' but not 'ia' (from a Latin root)   
11  Ends with 'on' (from a Greek root -- not 'tion')   
12                                    Ends with 'ex'   
13                                        Unchanging   
14                            Only the plural exists   
15                                    Compound nouns   

                          Rule for Forming the Plural  \
0                                 Add 'es' to the end   
1                                Add 'zes' to the end   
2                                          Add an 's'   
3                       Change the final 'y' to 'ies'   
4                     Change the 'f' or 'fe' to 'ves'   
5                                            Add 'es'   
6                                            Variable   
7                           Change final 'is' to 'es'   
8                            Change final 'us' to 'i'   
9                            Change final 'um' to 'a'   
10                           Change final 'a' to 'ae'   
11                           Change final 'on' to 'a'   
12                        Change final 'ex' to 'ices'   
13                   Singular and plural are the same   
14                                         Unchanging   
15  The plural ending is usually added to the main...   

                                             Examples  \
0   arch/arches, atlas/atlases, ax/axes, bash/bash...   
1   buzz/buzzes, fizz/fizzes, klutz/klutzes, quiz/...   
2   alley/alleys, attorney/attorneys, essay/essays...   
3   ally/allies, army/armies, baby/babies, beauty/...   
4   calf/calves, elf/elves, half/halves, hoof/hoov...   
5   buffalo/buffaloes, cargo/cargoes, echo/echoes,...   
6   child/children, die/dice, foot/feet, goose/gee...   
7   analysis/analyses, axis/axes, basis/bases, cri...   
8   alumnus/alumni, bacillus/bacilli, cactus/cacti...   
9   bacterium/bacteria, curriculum/curricula, datu...   
10  alga/algae, alumna/alumnae, antenna/antennae, ...   
11  automaton/automata, criterion/criteria, phenom...   
12                   vertex/vertices, vortex/vortices   
13  advice, aircraft, bison, corn, deer, equipment...   
14  barracks, bellows, cattle, congratulations, de...   
15  attorney general/attorneys general, bill of fa...   

                                           Exceptions  
0                                  axis/axes, ox/oxen  
1                                                 NaN  
2                                                 NaN  
3                                                 NaN  
4   belief/beliefs, chef/chefs, chief/chiefs, dwar...  
5   albino/albinos, armadillo/armadillos, auto/aut...  
6                                                 NaN  
7                                                 NaN  
8   abacus/abacuses, crocus/crocuses, genus/genera...  
9                      album/albums, stadium/stadiums  
10  agenda/agendas, alfalfa/alfalfas, aurora/auror...  
11  balloon/balloons, carton/cartons and many, man...  
12  annex/annexes, complex/complexes, duplex/duple...  
13                                                NaN  
14                                                NaN  
15                                                NaN

## Using an library

This doesn't work that good.

In [93]:
import inflect

p = inflect.engine()

In [95]:
for word in ['man', 'men', 'woman', 'women', 'dog', 'cat', 'flies', 'corpora']:
    print word, p.plural_noun( word )

man men
men mens
woman women
women womens
dog dogs
cat cats
flies fliess
corpora corporas


In [66]:
import inflect

# New Section

In [155]:
import requests

In [156]:
import urllib

In [157]:
url = urllib.urlencode({'properties': '{"annotators": "tokenize,ssplit,pos,parse", "outputFormat": "json"}'})
url

'properties=%7B%22annotators%22%3A+%22tokenize%2Cssplit%2Cpos%2Cparse%22%2C+%22outputFormat%22%3A+%22json%22%7D'

In [158]:
url1 = urllib.urlencode({'properties': '{"annotators": "pos", "outputFormat": "json"}'})
url1

'properties=%7B%22annotators%22%3A+%22pos%22%2C+%22outputFormat%22%3A+%22json%22%7D'

In [159]:
r = requests.post(url='http://10.129.2.170:9000/?' + url, 
              data='He failed to pay debt of the bank.')

In [160]:
json_data = r.json()

In [161]:
json_data

{u'sentences': [{u'basicDependencies': [{u'dep': u'ROOT',
     u'dependent': 2,
     u'dependentGloss': u'failed',
     u'governor': 0,
     u'governorGloss': u'ROOT'},
    {u'dep': u'nsubj',
     u'dependent': 1,
     u'dependentGloss': u'He',
     u'governor': 2,
     u'governorGloss': u'failed'},
    {u'dep': u'mark',
     u'dependent': 3,
     u'dependentGloss': u'to',
     u'governor': 4,
     u'governorGloss': u'pay'},
    {u'dep': u'xcomp',
     u'dependent': 4,
     u'dependentGloss': u'pay',
     u'governor': 2,
     u'governorGloss': u'failed'},
    {u'dep': u'dobj',
     u'dependent': 5,
     u'dependentGloss': u'debt',
     u'governor': 4,
     u'governorGloss': u'pay'},
    {u'dep': u'case',
     u'dependent': 6,
     u'dependentGloss': u'of',
     u'governor': 8,
     u'governorGloss': u'bank'},
    {u'dep': u'det',
     u'dependent': 7,
     u'dependentGloss': u'the',
     u'governor': 8,
     u'governorGloss': u'bank'},
    {u'dep': u'nmod',
     u'dependent': 8,
     u

In [162]:
json_data['sentences'][0].keys()

[u'tokens',
 u'index',
 u'enhancedDependencies',
 u'basicDependencies',
 u'parse',
 u'enhancedPlusPlusDependencies']

In [163]:
[(ob['word'], ob['index']) for ob in json_data['sentences'][0]['tokens']]

[(u'He', 1),
 (u'failed', 2),
 (u'to', 3),
 (u'pay', 4),
 (u'debt', 5),
 (u'of', 6),
 (u'the', 7),
 (u'bank', 8),
 (u'.', 9)]

In [168]:
tree = json_data['sentences'][0]['basicDependencies']
tree

[{u'dep': u'ROOT',
  u'dependent': 2,
  u'dependentGloss': u'failed',
  u'governor': 0,
  u'governorGloss': u'ROOT'},
 {u'dep': u'nsubj',
  u'dependent': 1,
  u'dependentGloss': u'He',
  u'governor': 2,
  u'governorGloss': u'failed'},
 {u'dep': u'mark',
  u'dependent': 3,
  u'dependentGloss': u'to',
  u'governor': 4,
  u'governorGloss': u'pay'},
 {u'dep': u'xcomp',
  u'dependent': 4,
  u'dependentGloss': u'pay',
  u'governor': 2,
  u'governorGloss': u'failed'},
 {u'dep': u'dobj',
  u'dependent': 5,
  u'dependentGloss': u'debt',
  u'governor': 4,
  u'governorGloss': u'pay'},
 {u'dep': u'case',
  u'dependent': 6,
  u'dependentGloss': u'of',
  u'governor': 8,
  u'governorGloss': u'bank'},
 {u'dep': u'det',
  u'dependent': 7,
  u'dependentGloss': u'the',
  u'governor': 8,
  u'governorGloss': u'bank'},
 {u'dep': u'nmod',
  u'dependent': 8,
  u'dependentGloss': u'bank',
  u'governor': 5,
  u'governorGloss': u'debt'},
 {u'dep': u'punct',
  u'dependent': 9,
  u'dependentGloss': u'.',
  u'gover

# extracting features from sentence

## verb_list

In [169]:
import re

In [170]:
verb_list = []
for i in json_data['sentences'][0]['tokens']:
    match = re.match(r'V(.*)',i['pos'])
    if match:
        verb_list.append(i['word'])
        

In [171]:
verb_list

[u'failed', u'pay']

## Finding common ancestor

In [172]:
nouns = []
for i in json_data['sentences'][0]['tokens']:
    match = re.match(r'NN(.*)',i['pos'])
    if match:
        nouns.append(i['word'])


In [173]:
nouns

[u'debt', u'bank']

In [174]:
for i in tree:
    print i

{u'dep': u'ROOT', u'dependent': 2, u'governorGloss': u'ROOT', u'governor': 0, u'dependentGloss': u'failed'}
{u'dep': u'nsubj', u'dependent': 1, u'governorGloss': u'failed', u'governor': 2, u'dependentGloss': u'He'}
{u'dep': u'mark', u'dependent': 3, u'governorGloss': u'pay', u'governor': 4, u'dependentGloss': u'to'}
{u'dep': u'xcomp', u'dependent': 4, u'governorGloss': u'failed', u'governor': 2, u'dependentGloss': u'pay'}
{u'dep': u'dobj', u'dependent': 5, u'governorGloss': u'pay', u'governor': 4, u'dependentGloss': u'debt'}
{u'dep': u'case', u'dependent': 6, u'governorGloss': u'bank', u'governor': 8, u'dependentGloss': u'of'}
{u'dep': u'det', u'dependent': 7, u'governorGloss': u'bank', u'governor': 8, u'dependentGloss': u'the'}
{u'dep': u'nmod', u'dependent': 8, u'governorGloss': u'debt', u'governor': 5, u'dependentGloss': u'bank'}
{u'dep': u'punct', u'dependent': 9, u'governorGloss': u'failed', u'governor': 2, u'dependentGloss': u'.'}


In [180]:
#path from NN to ROOT
path_head = []
dependancy_head = []
words = 'debt'
while (words!='ROOT'):
    for (idx,i) in enumerate(tree):
        if i['dependentGloss']==words:
            path_head.append(i['dependentGloss'])
            dependancy_head.append(i['dep'])
            words = i['governorGloss'] 
            index = idx
            break

In [181]:
#path from NN to ROOT
path_mod = []
dependancy_mod = []
words = 'bank'
while (words!='ROOT'):
    for (idx,i) in enumerate(tree):
        if i['dependentGloss']==words:
            path_mod.append(i['dependentGloss'])
            dependancy_mod.append(i['dep'])
            words = i['governorGloss'] 
            index = idx
            break

In [182]:
print path_head
print path_mod
print dependancy_head
print dependancy_mod

[u'debt', u'pay', u'failed']
[u'bank', u'debt', u'pay', u'failed']
[u'dobj', u'xcomp', u'ROOT']
[u'nmod', u'dobj', u'xcomp', u'ROOT']


In [183]:
res_head = zip(path_head,dependancy_head)
res_mod = zip(path_mod,dependancy_mod)
print res_head
print res_mod

[(u'debt', u'dobj'), (u'pay', u'xcomp'), (u'failed', u'ROOT')]
[(u'bank', u'nmod'), (u'debt', u'dobj'), (u'pay', u'xcomp'), (u'failed', u'ROOT')]


In [186]:
#common ancestor
flag=0
for i in res_head:
    if(flag==0):
        for j in res_mod:
            if i[0]==j[0]:
                print i[0]
                print rel1
                print rel2
                flag=1
                break
            else:
                rel2 = j[1]
    rel1 = i[1]

debt
ROOT
nmod


# TO-DO

Write a function which takes a noun compound (i.e., "student protest", "bank debt", "debt bank", etc) and a setence ("Thousands of students participated in series of protest in JNU.", "He failed to pay debt of a bank.") as inputs. It should return the common ancestor $c$ of the head and the modifier, dependency from $c$ towards the head, and dependecy from $c$ toards the modifier.